### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by JackPeterFletch** [awslabs/aws-serverless-ember#3]
Did you need to do anything to get this line to work?

I always get an error that providerArns expects a list of Strings, whereas I believe !GetAttr UserPool.Arn returns some kind of 'Object' type.

https://github.com/awslabs/aws-serverless-ember/blob/f8547cac6141efb0e2c55c08a9652bd3385b89fc/cloud/api.yaml#L244

**Comment by mlabieniec** [comment]
@JackPeterFletch hm, no I have not gotten this error. I'll check into it here and see if anything has changed with this property.

**Comment by officeguy** [comment]
Hi @mlabieniec,

great walkthrough. I have one question though as detailed here https://forums.aws.amazon.com/thread.jspa?threadID=274825
what tweak would be required in order to get only each users data returned, rather than all users data.

thanks

**Comment by mlabieniec** [comment]
Hi @officeguy, yes you could technically add the user ID (the cognito identity id) as a param in the dynamo query. There is a "mirror" of this solution done with mobile hub here:
https://github.com/aws-samples/aws-mobilehub-ember/blob/master/app/adapters/note.js#L44

This one actually does do the multi-tenancy and the dynamo queries are actually done on the client which could give you an idea on how to set that up. On here, you could add the 'user' field and use the lambda context as well:
https://github.com/aws-samples/aws-serverless-ember/blob/master/cloud/index.js#L32

If you end up adding it feel free to submit a PR as well here.

**Comment by mlabieniec** [comment]
Merged in PR #6 feel free to reopen
