### ISSUE TITLE
ember not loading resources

### ISSUE THREAD

**Issue by decentralisedkev** [awslabs/aws-serverless-ember#4]
When I load up ember with 'ember serve', 

I click login and it says 'Network failure'.

Checking the console in safari, I see:

[Error] Failed to load resource: A server with the specified hostname could not be found. (:.amazonaws.com, line 0)
[Error] XMLHttpRequest cannot load https://cognito-identity.us-east-1/:.amazonaws.com due to access control checks.

Checking it in Chrome, I see:

You are logged in with Cognito User Pools
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
credentials get error:  Error: Network Failure
    at XMLHttpRequest.<anonymous> (aws-sdk.js:124963)
(anonymous) @ aws.js:36

I can also confirm that when I enter a wrong password, it says incorrect. I only get network failure when I enter the correct password.

**Comment by mlabieniec** [comment]
@kevaundray did you setup your environment variables? It looks as though one may not be picked up:

https://github.com/awslabs/aws-serverless-ember#update-client-environment-variables

**Comment by decentralisedkev** [comment]
Thank you, that fixed it!
